// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://uvrccegyntmobhjlvjrg.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2cmNjZWd5bnRtb2Joamx2anJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI0MzEzOTUsImV4cCI6MjA0ODAwNzM5NX0.MpKrrbJG16ul97q5zYR2HqZPY0nnAwSTJmBcNmjy3sM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);